# Generated by Django 4.1 on 2022-08-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.CharField(max_length=50)),
                ('formacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Formacao',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='cidade',
            new_name='email',
        ),
    ]
