# Generated by Django 4.1 on 2022-08-31 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_curriculo_delete_formacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.candidato')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.curriculo')),
            ],
        ),
    ]
