# Generated by Django 4.1 on 2022-09-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='curriculo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nome',
        ),
        migrations.AddField(
            model_name='candidato',
            name='celular',
            field=models.IntegerField(default=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(default='exit', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_completo',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='password',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Curriculo',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
