# Generated by Django 4.1.1 on 2022-09-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('celular_empresa', models.CharField(max_length=11, unique=True)),
                ('email_empresa', models.CharField(max_length=50)),
                ('senha_empresa', models.CharField(max_length=20)),
            ],
        ),
    ]
