# Generated by Django 4.1.1 on 2022-09-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade_vaga', models.CharField(max_length=10000, unique=True)),
                ('requisitos_vagas', models.CharField(max_length=10000, unique=True)),
                ('beneficios_vagas', models.CharField(max_length=10000, unique=True)),
                ('valores_vagas', models.CharField(max_length=500)),
                ('descricao_participacao_vagas', models.CharField(max_length=10000)),
            ],
        ),
    ]
