# Generated by Django 4.1.1 on 2022-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0003_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('escolaridade', models.CharField(max_length=100)),
                ('experiencia', models.CharField(max_length=255)),
                ('projetos', models.CharField(max_length=255)),
                ('cursos', models.CharField(max_length=255)),
                ('idiomas', models.CharField(max_length=255)),
                ('valores_pessoais', models.CharField(max_length=255)),
                ('descricao_participacao', models.CharField(max_length=255)),
                ('descricao_valores_empresa', models.CharField(max_length=255)),
                ('portfolio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
    ]
