# Generated by Django 4.1.1 on 2022-09-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0005_alter_candidato_celular_alter_empresa_razao_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='candidato',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.candidato'),
        ),
    ]
