# Generated by Django 4.1.1 on 2022-09-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0007_remove_formulario_candidato_formulario_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='candidato',
        ),
        migrations.AddField(
            model_name='formulario',
            name='candidato',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.candidato'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tinder.empresa'),
        ),
    ]
