# Generated by Django 4.1.1 on 2022-09-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0008_remove_formulario_empresa_remove_vaga_candidato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='atividade_vaga',
            new_name='atividade_vagas',
        ),
    ]
