# Generated by Django 4.1.1 on 2022-09-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0009_rename_atividade_vaga_vaga_atividade_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='empresa',
        ),
    ]
